version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.go
    ports:
      - "8080:8080"
  client:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"